-- CW2: the CRUSADER WARS II lobby in Three Kingdoms' main menu.
-- Loaded by 3K's script/frontend_mod_scripting.lua, only while CW2's pack is enabled.
--
-- 1. Adds BATTLE > CRUSADER WARS II to the main menu (the game's own menu item
--    template, ui/templates/3k_btn_menu_item_text), after MULTIPLAYER.
-- 2. The entry opens the lobby (ui/cw2/cw2_lobby.twui.xml, generated by lobby/lobby.py):
--    both CK3 sides and the staged Three Kingdoms roll. It also opens by itself the
--    first time the main menu shows while this run's battle is still unfought.
-- 3. FIGHT closes the lobby and opens the staged battle through the game's own
--    screens (ui/frontend ui/*.twui.xml):
--      main.twui.xml               btn_new_battle
--      new_battle.twui.xml         button_historical_battle
--      historical_battles.twui.xml list_box row for Xingyang (the screen opens on Xiapi),
--                                  checkbox_romance_mode off (the pack replaces Records only),
--                                  button_start_battle
-- The frontend's UI calls, timer and event names are not in any pack, so every engine
-- call is guarded and every step is logged to the run folder. If the lobby cannot be
-- built, the player can still open Battle > New > Historical Battle > Xingyang by hand.
local run_id = "@@RUN_ID@@";
local battle_log = "@@OUTPUT_PATH@@";
local log_path = "@@FRONTEND_LOG@@";
local LAYOUT = "@@LAYOUT@@";
local CARD = @@LOBBY@@;
local TICK_MS = 500;
local FIGHT_TICKS = 240;     -- two minutes to reach the battle after FIGHT
local COOLDOWN_TICKS = 3;    -- let a screen transition finish after a click
local MENU_ID = "cw2_menu_entry";
local MENU_LABEL = "CRUSADER WARS II";
local UNIT_ROWS = 6;
local BUTTON_STATES = {"active", "hover", "down", "down_off", "selected", "selected_hover", "inactive"};

local ticks, cooldown = 0, 0;
local has_timer = false;
local fighting, fight_done = false, false;
local row_clicked = false;
local auto_opened = false;
local menu_entry, lobby = nil, nil;
local SEARCH_EVERY = 4;       -- full UI-tree searches for the menu run every 4th tick at most
local search_wait = 0;

local function log(text)
    local ok, stamp = pcall(os.date, "%H:%M:%S ");
    local file = io.open(log_path, "a");
    if file then
        file:write((ok and stamp or "") .. tostring(text) .. "\n");
        file:close();
    end;
end;

local function exists(path)
    local file = io.open(path, "r");
    if file then file:close(); return true; end;
    return false;
end;

local function fought() return exists(battle_log); end;

local function ui_root()
    if core and core.get_ui_root then
        local ok, root = pcall(core.get_ui_root, core);
        if ok and root then return root; end;
    end;
    return rawget(_G, "m_root");
end;

-- Component id, or nil. A dead or odd component must not stop a tree walk.
local function id_of(uic)
    local ok, id = pcall(function() return uic:Id(); end);
    return ok and type(id) == "string" and id or nil;
end;

local function children(uic)
    local list = {};
    local ok, count = pcall(function() return uic:ChildCount(); end);
    if not ok or type(count) ~= "number" then return list; end;
    for i = 0, count - 1 do
        local got, child = pcall(function() return UIComponent(uic:Find(i)); end);
        if got and child then list[#list + 1] = child; end;
    end;
    return list;
end;

local function find(uic, id, depth)
    depth = depth or 0;
    if not uic or depth > 40 then return nil; end;
    if id_of(uic) == id then return uic; end;
    for _, child in ipairs(children(uic)) do
        local hit = find(child, id, depth + 1);
        if hit then return hit; end;
    end;
    return nil;
end;

local function visible(uic)
    local ok, shown = pcall(function() return uic:VisibleFromRoot(); end);
    if ok then return shown; end;
    ok, shown = pcall(function() return uic:Visible(); end);
    return ok and shown;
end;

local function alive(uic, id)
    return uic ~= nil and id_of(uic) == id;
end;

local function dump(uic, depth, lines)
    if depth > 8 then return; end;
    table.insert(lines, string.rep("  ", depth) .. tostring(id_of(uic)) .. (visible(uic) and "" or " (hidden)"));
    for _, child in ipairs(children(uic)) do dump(child, depth + 1, lines); end;
end;

local function dump_tree(reason)
    local root = ui_root();
    if not root then log("dump skipped: no UI root"); return; end;
    local lines = {};
    local ok, err = pcall(dump, root, 0, lines);
    log(reason .. "; component tree follows" .. (ok and "" or (" (partial: " .. tostring(err) .. ")")));
    log(table.concat(lines, "\n"));
end;

local function click(uic, what)
    uic:SimulateLClick();
    cooldown = has_timer and COOLDOWN_TICKS or 0;
    log("clicked " .. what);
end;

local function label(uic)
    local ok, text = pcall(function() return uic:GetStateText(); end);
    return ok and type(text) == "string" and text or "";
end;

local function set_text(uic, text)
    return uic and pcall(function() uic:SetStateText(text); end);
end;

-- Buttons keep a text per state, so write the label into every state.
local function set_button_text(uic, text)
    for _, state in ipairs(BUTTON_STATES) do
        if pcall(function() uic:SetState(state); end) then set_text(uic, text); end;
    end;
    pcall(function() uic:SetState("active"); end);
end;

local function fmt(n)
    if type(n) ~= "number" then return "-"; end;
    local s = tostring(math.floor(n + 0.5));
    local sign = s:sub(1, 1) == "-" and "-" or "";
    local grouped = s:sub(#sign + 1):reverse():gsub("(%d%d%d)", "%1,"):reverse();
    return sign .. grouped:gsub("^,", "");
end;

-- ---- main menu entry ----------------------------------------------------

-- Put our entry straight after `anchor` in its list by re-adopting the siblings that follow.
local function move_after(group, entry, anchor_id)
    local after, seen = {}, false;
    for _, child in ipairs(children(group)) do
        local id = id_of(child);
        if seen and id ~= MENU_ID then after[#after + 1] = child; end;
        if id == anchor_id then seen = true; end;
    end;
    local ok, err = pcall(function()
        for _, child in ipairs(after) do group:Divorce(child:Address()); end;
        for _, child in ipairs(after) do group:Adopt(child:Address()); end;
    end);
    log(ok and "menu entry placed after " .. anchor_id or "menu entry left at the end of the list: " .. tostring(err));
end;

local function add_menu_entry(root)
    if alive(menu_entry, MENU_ID) then return menu_entry; end;
    menu_entry = find(root, MENU_ID);
    if menu_entry then return menu_entry; end;
    local anchor = find(root, "btn_multiplayer_battle") or find(root, "btn_new_battle");
    if not anchor or not visible(anchor) then return nil; end;
    local ok, group = pcall(function() return UIComponent(anchor:Parent()); end);
    if not ok or not group then log("menu entry skipped: no menu list"); return nil; end;
    local made, address = pcall(function()
        return group:CreateComponent(MENU_ID, "ui/templates/3k_btn_menu_item_text");
    end);
    if not made or not address then log("menu entry not created: " .. tostring(address)); return nil; end;
    menu_entry = UIComponent(address);
    set_button_text(menu_entry, MENU_LABEL);
    move_after(group, menu_entry, id_of(anchor));
    log("menu entry added");
    return menu_entry;
end;

-- ---- the lobby ------------------------------------------------------------

local function part(id) return lobby and find(lobby, id); end;

local function fill_side(prefix, side)
    side = side or {};
    local function put(id, text) set_text(part("cw2_" .. prefix .. "_" .. id), text); end;
    put("yours", side.yours and "YOUR ARMY" or "");
    put("name", side.commander or side.role or "");
    put("martial", side.martial and tostring(side.martial) or "-");
    put("prowess", side.prowess and tostring(side.prowess) or "-");
    put("men", fmt(side.ck3_men));
    local generals = side.generals and #side.generals or 0;
    put("staged", fmt(side.men) .. " in Three Kingdoms, " .. generals .. (generals == 1 and " general" or " generals"));
    local units = side.units or {};
    local shown = #units > UNIT_ROWS and UNIT_ROWS - 1 or #units;
    for i = 0, UNIT_ROWS - 1 do
        local unit = units[i + 1];
        local name, men = "", "";
        if i < shown and unit then
            name = unit.name .. (unit.cards > 1 and (" x" .. unit.cards) or "");
            men = fmt(unit.men);
        elseif i == shown and #units > shown then
            local rest = 0;
            for j = shown + 1, #units do rest = rest + units[j].men; end;
            name, men = "and " .. (#units - shown) .. " more kinds", fmt(rest);
        end;
        put("u" .. i .. "_name", name);
        put("u" .. i .. "_men", men);
    end;
end;

local function refresh_lobby()
    set_text(part("cw2_battle"), CARD.battle or "CK3 battle");
    set_text(part("cw2_date"), CARD.date or "-");
    set_text(part("cw2_season"), CARD.season or "-");
    set_text(part("cw2_roll"), "LOCKED");
    set_text(part("cw2_seed"), (CARD.mode or "Records") .. " roll, seed " .. tostring(CARD.seed or "-"));
    set_text(part("cw2_note"), "Shuffle and lock in the Crusader Wars 2 launcher: Three Kingdoms loads one staged roll per launch.");
    fill_side("a", CARD.sides and CARD.sides[1]);
    fill_side("d", CARD.sides and CARD.sides[2]);
    for _, id in ipairs({"cw2_btn_shuffle", "cw2_btn_lock"}) do
        local button = part(id);
        pcall(function() button:SetState("inactive"); end);
        pcall(function() button:SetTooltipText("Rolls are made in the Crusader Wars 2 launcher before Three Kingdoms starts.", true); end);
    end;
    local done = fought();
    pcall(function() part("cw2_btn_fight"):SetState(done and "inactive" or "active"); end);
    set_text(part("cw2_status"), done and "This battle has been fought. In the launcher, read the result, then press Return to CK3."
        or "Armies ready for battle");
end;

local function open_lobby(reason)
    local root = ui_root();
    if not root then return false; end;
    if not alive(lobby, "cw2_lobby") then lobby = find(root, "cw2_lobby"); end;
    if not lobby then
        for _, path in ipairs({LAYOUT, LAYOUT .. ".twui.xml"}) do
            local ok, address = pcall(function() return root:CreateComponent("cw2_lobby", path); end);
            if ok and address then lobby = UIComponent(address); log("lobby built from " .. path); break; end;
            log("lobby layout " .. path .. " not loaded: " .. tostring(address));
        end;
    end;
    if not lobby then log("lobby unavailable; open Historical Battles > Xingyang by hand"); return false; end;
    local ok, err = pcall(refresh_lobby);
    if not ok then log("lobby text: " .. tostring(err)); end;
    pcall(function() lobby:SetVisible(true); end);
    pcall(function() lobby:PropagatePriority(200); end);
    log("lobby opened (" .. reason .. ")");
    return true;
end;

local function close_lobby()
    if lobby then pcall(function() lobby:SetVisible(false); end); end;
end;

-- ---- FIGHT: open the staged battle through the game's own screens ----------

local function xinyang_row(root)
    local list = find(root, "list_box");
    if not list then return nil; end;
    for _, row in ipairs(children(list)) do
        -- Rows are built from template_battle and labelled "NAME (KEY)".
        if string.find(string.lower(tostring(id_of(row)) .. " " .. label(row)), "xinyang", 1, true) then return row; end;
    end;
    return nil;
end;

local function romance_on(box)
    local ok, state = pcall(function() return box:CurrentState(); end);
    return ok and type(state) == "string" and string.find(string.lower(state), "selected", 1, true) ~= nil;
end;

local function stop_fight(text)
    fighting, fight_done = false, true;
    log(text);
end;

local function historical_screen(root, start)
    if not row_clicked then
        local row = xinyang_row(root);
        if not row then
            dump_tree("no Xingyang row in list_box");
            stop_fight("stopped: will not start another battle; open Xingyang by hand");
            return;
        end;
        click(row, "Xingyang row " .. tostring(id_of(row)));
        row_clicked = true;
        return;
    end;
    local box = find(root, "checkbox_romance_mode");
    if box and visible(box) and romance_on(box) then
        click(box, "romance checkbox off");
        return;
    end;
    click(start, "button_start_battle");
    stop_fight("battle requested for run " .. run_id);
end;

local function fight_step(root)
    ticks = ticks + 1;
    if ticks > FIGHT_TICKS then
        dump_tree("gave up after " .. FIGHT_TICKS .. " polls");
        stop_fight("stopped: open Historical Battles > Xingyang by hand");
        return;
    end;
    if cooldown > 0 then cooldown = cooldown - 1; return; end;
    local start = find(root, "button_start_battle");
    if start and visible(start) then historical_screen(root, start); return; end;
    local historical = find(root, "button_historical_battle");
    if historical and visible(historical) then click(historical, "button_historical_battle"); return; end;
    local new_battle = find(root, "btn_new_battle");
    if new_battle and visible(new_battle) then click(new_battle, "btn_new_battle"); return; end;
end;

local function fight()
    if fought() then log("FIGHT ignored: run " .. run_id .. " was already fought"); return; end;
    close_lobby();
    fighting, ticks, cooldown, row_clicked = true, 0, 0, false;
    log("FIGHT: opening the staged battle for run " .. run_id);
end;

-- ---- drivers -------------------------------------------------------------

local function step()
    local root = ui_root();
    if not root then return; end;
    if fighting then fight_step(root); return; end;
    if alive(menu_entry, MENU_ID) and auto_opened then return; end;
    if search_wait > 0 then search_wait = search_wait - 1; return; end;
    search_wait = SEARCH_EVERY - 1;
    add_menu_entry(root);
    if auto_opened or fight_done or fought() then return; end;
    local menu = find(root, "btn_new_battle");
    if menu and visible(menu) then
        auto_opened = true;
        open_lobby("a staged battle is waiting");
    end;
end;

local function safe_step()
    local ok, err = pcall(step);
    if not ok then log("error: " .. tostring(err)); end;
end;

local ACTIONS = {
    [MENU_ID] = function() open_lobby("menu"); end,
    cw2_btn_back = close_lobby,
    cw2_btn_fight = fight,
};

local function on_click(context)
    local id = context and context.string;
    local action = ACTIONS[id];
    if not action then return; end;
    local ok, err = pcall(action);
    if not ok then log("error in " .. tostring(id) .. ": " .. tostring(err)); end;
end;

log("CW2 lobby loaded for run " .. run_id .. (fought() and " (already fought)" or ""));

-- Drivers: a repeating real-time timer when the frontend has one, plus UI events.
if core and core.add_listener then
    pcall(function()
        core:add_listener("cw2_lobby_tick", "RealTimeTrigger",
            function(context) return context.string == "cw2_lobby_tick"; end,
            safe_step, true);
    end);
    if real_timer and real_timer.register_repeating then
        has_timer = pcall(real_timer.register_repeating, "cw2_lobby_tick", TICK_MS);
    end;
    for _, event in ipairs({"UICreated", "FrontendScreenTransition"}) do
        pcall(function()
            core:add_listener("cw2_lobby_" .. event, event, true, safe_step, true);
        end);
    end;
    pcall(function()
        core:add_listener("cw2_lobby_click", "ComponentLClickUp",
            function(context) return ACTIONS[context.string] ~= nil; end, on_click, true);
    end);
end;
if not has_timer and tm and tm.repeat_callback then
    has_timer = pcall(function() tm:repeat_callback(safe_step, TICK_MS, "cw2_lobby_tick"); end);
end;
log(has_timer and "polling every " .. TICK_MS .. " ms" or "no frontend timer; acting on UI events only");
